version: '3.9'

services:
    php-httpd:
        image: php:8.0-apache
        ports:
            - 80:80
        volumes:
            - ./www:/var/www/html

    mariadb:
        image: mariadb:10.6.8
        volumes:
            - vol-mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "myuser"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: "user"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - 8181:80

volumes:

    vol-mariadb: